version: "3.8"

networks:
    sap_net:
        driver: bridge
services:
    sap_web:
        env_file: ./.env
        image: sap/sap_web
        build:
            context: ./sap_web
        container_name: sap_web
        ports:
            - "${HOST_HTTP_DEV_PORT}:8000"
        networks:
            - sap_net
        #entrypoint: ["sh","/app/sap_web/entrypoint.sh"]
        command: tail -f /dev/null
        volumes:
            - ./sap_web:/app/sap_web
            - ${STATICS_VOLUME}:/app/statics
            - ${MEDIA_VOLUME}:/app/media
