version: "3.8"

networks:
    sap_net:
        driver: bridge
services:
  sap_db:
    env_file: ./.env
    image: postgres:alpine
    container_name: sap_db
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - sap_net
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
      
  sap_web:
    env_file: ./.env
    image: sap/sap_web
    build:
      context: ./sap_web
    container_name: sap_web
    ports:
      - "${HOST_HTTP_DEV_PORT}:8000"
    networks:
      - sap_net
    #entrypoint: ["sh","/sap/sap_web/entrypoint.sh"]
    command: tail -f /dev/null
    volumes:
      - ./sap_web:/app/sap_web
    depends_on:
      - sap_db
  
  sap_proxy:
    env_file: ./.env
    image: sap/sap_proxy
    build:
        context: ./sap_proxy
    container_name: sap_proxy
    networks:
        - sap_net
    ports:
        - "${HOST_HTTP_PORT}:80"
    depends_on:
        - sap_web
