# Generated by Django 3.1.3 on 2020-11-10 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('datacollector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexam',
            name='exam',
            field=models.CharField(choices=[('0', 'Emoglobina'), ('1', 'Leucocitos'), ('2', 'Plaquetas')], max_length=2, verbose_name='Exame'),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='result',
            field=models.FloatField(verbose_name='Resultado'),
        ),
        migrations.CreateModel(
            name='ClinicalMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_change', models.BooleanField(verbose_name='Alterações Visuais')),
                ('body_weight', models.CharField(choices=[('0', 'Manutenção do Peso'), ('1', 'Perda de Peso'), ('2', 'Ganho de Peso')], max_length=1, verbose_name='Peso Corporal')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Acompanhamento Clínico',
                'verbose_name_plural': 'Acompanhamentos Clínicos',
            },
        ),
    ]
